#!/usr/bin/env python
# tab-width: 4


import sys
import socket
import time

to_hosts = "gkrellm4,rpi0,rpi1"

repeat = 4
delay = .05


from_host = socket.gethostname()

# The dav multicast group IP and port number is fixed:
PKC_MULTICAST_GROUP = '225.0.0.55'
PKC_MULTICAST_PORT  = 22555
send_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
send_socket.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)

msg_id = 1
for x in range(0, repeat):
    msg = "%s:%d %s message alarm" % (from_host, msg_id, to_hosts)
#    print msg
    send_socket.sendto(msg, (PKC_MULTICAST_GROUP, PKC_MULTICAST_PORT))
    time.sleep(delay)
