#!/usr/bin/env python
# tab-width: 4

import sys
import socket
import time


to_hosts = "gkrellm4,rpi0,rpi1"
motion_region = 3
magnitude_limit = 12
count_limit = 20
holdoff = 6


repeat = 4
delay = .05

from_host = socket.gethostname()



PKC_MULTICAST_GROUP = '225.0.0.55'
PKC_MULTICAST_PORT  = 22555
send_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
send_socket.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)

filename = '/run/dav/motion-events'
file = open(filename,'r')

msg_id = 1

state = 'wait'
tsent = 0

while 1:
	where = file.tell()
	line = file.readline()
	if not line:
		time.sleep(0.1)
		file.seek(where)
		continue
	line = line.strip('\n')
#	print '==>' + line
	if (line.find('<motion') == 0):
		state = 'motion'
	elif (line.find('</motion>') == 0):
		state = 'wait'
	elif (line.find('<end>') == 0):
		sys.exit(1)
	elif (state == 'motion'):
		if (line.startswith(str(motion_region))):
#			print line
			tnow = time.time()
			if (tnow >= tsent + holdoff):
				r, x, y, dx, dy, mag, count = line.split()
				if (int(mag) >= magnitude_limit and int(count) >= count_limit):
					for x in range(0, repeat):
						msg = "%s:%d %s message alarm" % (from_host, msg_id, to_hosts)
#						 print msg
						send_socket.sendto(msg, (PKC_MULTICAST_GROUP, PKC_MULTICAST_PORT))
						time.sleep(delay)
					tsent = tnow
					msg_id = msg_id + 1

