#!/usr/bin/env python
# tab-width: 4

import socket
import struct
import os
import time

audio_command = "aplay /home/pi/audio/danger-will-robinson.wav &"

holdoff = 5



PKC_MULTICAST_GROUP_IP   = '225.0.0.55'
PKC_MULTICAST_GROUP_PORT = 22555

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind((PKC_MULTICAST_GROUP_IP, PKC_MULTICAST_GROUP_PORT))
mreq = struct.pack("4sl", socket.inet_aton(PKC_MULTICAST_GROUP_IP), socket.INADDR_ANY)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)

id = 0
idprev = 0
tprev = 0
tplay = 0

this_host = socket.gethostname()

def host_match(from_host, to_hosts):
	if ('all' in to_hosts.lower()): 
		if ('!' in to_hosts):
			return from_host != this_host
		else:
			return True
	host_list = to_hosts.split(',')
	if (this_host in host_list):
		return True
	return False


while True:
	line = sock.recv(256)
	tnow = time.time()
#	print line

	from_host, to_hosts, msg_type, msg_body = line.split(' ', 3)
	if (msg_type != 'message' or msg_body != 'alarm'):
		continue;

	idx = from_host.find(':')
	if (idx >= 0):
		from_host, ids = from_host.split(':')
		id = int(ids)

	if (host_match(from_host, to_hosts) == False):
		continue

	# reject repeat messages of same msg_id.
	if (id == idprev and tnow - tprev <= 2):
		tprev = tnow
		continue

	if (id != idprev or tnow - tplay >= holdoff):
		print audio_command
		os.system(audio_command)
		tplay = tnow

	idprev = id

