#!/usr/bin/env python
# tab-width: 4

import sys
import socket
import time

PKC_MULTICAST_GROUP = '225.0.0.55'
PKC_MULTICAST_PORT  = 22555

send_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
send_socket.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)

repeat = 4
delay = .05

def usage():
	print "usage: pkc-reboot <host|host-list|all>"
	print "Multicast a reboot command to davs on a LAN."
	print "    host, host-list or all must be given."
	print "    host-list is a comma separated list of hosts."
	sys.exit()

argc = len(sys.argv)
if argc == 1:
	usage()
elif argc == 2:
	hosts = sys.argv[1]
else:
	print 'Bad number of args'
	usage()

hostname = socket.gethostname()

msg_id = 1
for x in range(0, repeat):
	msg = "%s:%d %s command @reboot" % (hostname, msg_id, hosts)
#	print msg
	send_socket.sendto(msg, (PKC_MULTICAST_GROUP, PKC_MULTICAST_PORT))
	time.sleep(delay)


time.sleep(1)
msg_id = 2
for x in range(0, repeat):
	msg = "%s:%d %s command @reboot" % (hostname, msg_id, hosts)
#	print msg
	send_socket.sendto(msg, (PKC_MULTICAST_GROUP, PKC_MULTICAST_PORT))
	time.sleep(delay)
